# Copyright 2025 Veloxpack.io
FROM --platform=$BUILDPLATFORM golang:1.27.0 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/volume-recovery-operator/ cmd/volume-recovery-operator/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
    go build -trimpath \
    -o volume-recovery-operator \
    cmd/volume-recovery-operator/main.go

FROM registry.k8s.io/build-image/debian-base:bookworm-v1.0.7
COPY --from=builder /workspace/volume-recovery-operator /volume-recovery-operator
ENTRYPOINT ["/volume-recovery-operator"]
